/* Generated By:JavaCC: Do not edit this line. WebMotionConstants.java */
package org.debux.webmotion.netbeans.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WebMotionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SECTION_CONFIG = 1;
  /** RegularExpression Id. */
  int SECTION_ACTIONS = 2;
  /** RegularExpression Id. */
  int SECTION_ERRORS = 3;
  /** RegularExpression Id. */
  int SECTION_FILTERS = 4;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES = 5;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int METHOD_HTTP = 7;
  /** RegularExpression Id. */
  int WHITESPACE = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int LETTER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[config]\"",
    "\"[actions]\"",
    "\"[errors]\"",
    "\"[filters]\"",
    "<SECTION_PROPERTIES>",
    "<COMMENT>",
    "<METHOD_HTTP>",
    "<WHITESPACE>",
    "<DIGIT>",
    "<LETTER>",
    "<token of kind 11>",
  };

}
