package org.debux.webmotion.netbeans.javacc;

/* Generated By:JavaCC: Do not edit this line. WebMotionConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WebMotionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int SECTION_CONFIG = 3;
  /** RegularExpression Id. */
  int SECTION_ACTIONS = 4;
  /** RegularExpression Id. */
  int LETTER = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"[config]\"",
    "\"[actions]\"",
    "<LETTER>",
  };

}
