/* Generated By:JavaCC: Do not edit this line. WebMotionParserConstants.java */
package org.debux.webmotion.netbeans.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WebMotionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SECTION_CONFIG = 1;
  /** RegularExpression Id. */
  int SECTION_ACTIONS = 2;
  /** RegularExpression Id. */
  int SECTION_ERRORS = 3;
  /** RegularExpression Id. */
  int SECTION_FILTERS = 4;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS = 5;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES = 6;
  /** RegularExpression Id. */
  int CONFIG_NAME = 7;
  /** RegularExpression Id. */
  int ACTION_JAVA = 8;
  /** RegularExpression Id. */
  int ACTION_URL = 9;
  /** RegularExpression Id. */
  int ACTION_VIEW = 10;
  /** RegularExpression Id. */
  int COMMENT = 11;
  /** RegularExpression Id. */
  int METHODS_HTTP = 12;
  /** RegularExpression Id. */
  int METHOD_HTTP = 13;
  /** RegularExpression Id. */
  int EQUALS = 14;
  /** RegularExpression Id. */
  int NEW_LINE = 15;
  /** RegularExpression Id. */
  int WHITESPACE = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int LETTER = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"[config]\"",
    "\"[actions]\"",
    "\"[errors]\"",
    "\"[filters]\"",
    "\"[extensions]\"",
    "<SECTION_PROPERTIES>",
    "<CONFIG_NAME>",
    "<ACTION_JAVA>",
    "<ACTION_URL>",
    "\"view:\"",
    "<COMMENT>",
    "<METHODS_HTTP>",
    "<METHOD_HTTP>",
    "\"=\"",
    "<NEW_LINE>",
    "<WHITESPACE>",
    "<DIGIT>",
    "<LETTER>",
    "<token of kind 19>",
    "<token of kind 20>",
  };

}
