/* Generated By:JavaCC: Do not edit this line. WebMotionParserConstants.java */
package org.debux.webmotion.netbeans.javacc.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WebMotionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 1;
  /** RegularExpression Id. */
  int COMMENT_IN_CONFIG = 2;
  /** RegularExpression Id. */
  int COMMENT_IN_ACTIONS = 3;
  /** RegularExpression Id. */
  int COMMENT_IN_ERRORS = 4;
  /** RegularExpression Id. */
  int COMMENT_IN_FILTERS = 5;
  /** RegularExpression Id. */
  int COMMENT_IN_EXTENSIONS = 6;
  /** RegularExpression Id. */
  int COMMENT_IN_PROPERTIES = 7;
  /** RegularExpression Id. */
  int SECTION_CONFIG_NAME = 8;
  /** RegularExpression Id. */
  int SECTION_ACTIONS_NAME = 9;
  /** RegularExpression Id. */
  int SECTION_ERRORS_NAME = 10;
  /** RegularExpression Id. */
  int SECTION_FILTERS_NAME = 11;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS_NAME = 12;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES_NAME = 13;
  /** RegularExpression Id. */
  int METHODS_HTTP = 14;
  /** RegularExpression Id. */
  int METHOD_HTTP = 15;
  /** RegularExpression Id. */
  int ACTION_BASIC_JAVA = 16;
  /** RegularExpression Id. */
  int ACTION_JAVA = 17;
  /** RegularExpression Id. */
  int ACTION_VIEW = 18;
  /** RegularExpression Id. */
  int ACTION_LINK = 19;
  /** RegularExpression Id. */
  int VARIABLE = 20;
  /** RegularExpression Id. */
  int PATTERN = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;
  /** RegularExpression Id. */
  int QUALIFIED_IDENTIFIER = 23;
  /** RegularExpression Id. */
  int NEW_LINE = 24;
  /** RegularExpression Id. */
  int WHITESPACE = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int LETTER = 27;
  /** RegularExpression Id. */
  int SECTION_CONFIG_NEXT_CONFIG = 28;
  /** RegularExpression Id. */
  int SECTION_CONFIG_NEXT_ACTIONS = 29;
  /** RegularExpression Id. */
  int SECTION_CONFIG_NEXT_ERRORS = 30;
  /** RegularExpression Id. */
  int SECTION_CONFIG_NEXT_FILTERS = 31;
  /** RegularExpression Id. */
  int SECTION_CONFIG_NEXT_EXTENSIONS = 32;
  /** RegularExpression Id. */
  int SECTION_CONFIG_NEXT_PROPERTIES = 33;
  /** RegularExpression Id. */
  int CONFIG_KEY = 34;
  /** RegularExpression Id. */
  int CONFIG_EQUALS = 35;
  /** RegularExpression Id. */
  int CONFIG_VALUE = 36;
  /** RegularExpression Id. */
  int CONFIG_END = 37;
  /** RegularExpression Id. */
  int SECTION_ACTIONS_NEXT_CONFIG = 38;
  /** RegularExpression Id. */
  int SECTION_ACTIONS_NEXT_ACTIONS = 39;
  /** RegularExpression Id. */
  int SECTION_ACTIONS_NEXT_ERRORS = 40;
  /** RegularExpression Id. */
  int SECTION_ACTIONS_NEXT_FILTERS = 41;
  /** RegularExpression Id. */
  int SECTION_ACTIONS_NEXT_EXTENSIONS = 42;
  /** RegularExpression Id. */
  int SECTION_ACTIONS_NEXT_PROPERTIES = 43;
  /** RegularExpression Id. */
  int ACTION_METHOD = 44;
  /** RegularExpression Id. */
  int ACTION_PATH = 45;
  /** RegularExpression Id. */
  int ACTION_PATH_VARIABLE = 46;
  /** RegularExpression Id. */
  int ACTION_PARAMETERS_BEGIN = 47;
  /** RegularExpression Id. */
  int ACTION_ACTION_JAVA_BEGIN = 48;
  /** RegularExpression Id. */
  int ACTION_ACTION_JAVA = 49;
  /** RegularExpression Id. */
  int ACTION_ACTION_VIEW = 50;
  /** RegularExpression Id. */
  int ACTION_ACTION_LINK = 51;
  /** RegularExpression Id. */
  int ACTION_SEPARATOR = 52;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_NAME = 53;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_EQUALS = 54;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_OTHER = 55;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_SEPARATOR = 56;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_VALUE = 57;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_VALUE_VARIABLE = 58;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_VALUE_OTHER = 59;
  /** RegularExpression Id. */
  int ACTION_PATH_PARAMETER_VALUE_SEPARATOR = 60;
  /** RegularExpression Id. */
  int ACTION_ACTION_JAVA_QUALIFIED_IDENTIFIER = 61;
  /** RegularExpression Id. */
  int ACTION_ACTION_JAVA_IDENTIFIER = 62;
  /** RegularExpression Id. */
  int ACTION_ACTION_JAVA_SEPARATOR = 63;
  /** RegularExpression Id. */
  int ACTION_ACTION_JAVA_END = 64;
  /** RegularExpression Id. */
  int ACTION_ACTION_VIEW_VALUE = 65;
  /** RegularExpression Id. */
  int ACTION_ACTION_VIEW_SEPARATOR = 66;
  /** RegularExpression Id. */
  int ACTION_ACTION_VIEW_END = 67;
  /** RegularExpression Id. */
  int ACTION_ACTION_LINK_VALUE = 68;
  /** RegularExpression Id. */
  int ACTION_ACTION_LINK_SEPARATOR = 69;
  /** RegularExpression Id. */
  int ACTION_ACTION_LINK_END = 70;
  /** RegularExpression Id. */
  int ACTION_PARAMETERS_SEPARATOR = 71;
  /** RegularExpression Id. */
  int ACTION_PARAMETER_NAME = 72;
  /** RegularExpression Id. */
  int ACTION_PARAMETER_EQUALS = 73;
  /** RegularExpression Id. */
  int ACTION_PARAMETER_SEPARATOR = 74;
  /** RegularExpression Id. */
  int ACTION_END = 75;
  /** RegularExpression Id. */
  int ACTION_PARAMETER_VALUE = 76;
  /** RegularExpression Id. */
  int ACTION_PARAMETER_VALUE_SEPARATOR = 77;
  /** RegularExpression Id. */
  int ACTION_PARAMETER_VALUE_END = 78;
  /** RegularExpression Id. */
  int SECTION_ERRORS_NEXT_CONFIG = 79;
  /** RegularExpression Id. */
  int SECTION_ERRORS_NEXT_ACTIONS = 80;
  /** RegularExpression Id. */
  int SECTION_ERRORS_NEXT_ERRORS = 81;
  /** RegularExpression Id. */
  int SECTION_ERRORS_NEXT_FILTERS = 82;
  /** RegularExpression Id. */
  int SECTION_ERRORS_NEXT_EXTENSIONS = 83;
  /** RegularExpression Id. */
  int SECTION_ERRORS_NEXT_PROPERTIES = 84;
  /** RegularExpression Id. */
  int CODE = 85;
  /** RegularExpression Id. */
  int ERROR_CODE = 86;
  /** RegularExpression Id. */
  int ALL = 87;
  /** RegularExpression Id. */
  int EXCEPTION = 88;
  /** RegularExpression Id. */
  int ERROR_SEPARATOR = 89;
  /** RegularExpression Id. */
  int ERROR_ACTION_JAVA_BEGIN = 90;
  /** RegularExpression Id. */
  int ERROR_ACTION_VIEW_BEGIN = 91;
  /** RegularExpression Id. */
  int ERROR_ACTION_LINK_BEGIN = 92;
  /** RegularExpression Id. */
  int ERROR_ACTION_JAVA = 93;
  /** RegularExpression Id. */
  int ERROR_ACTION_VIEW = 94;
  /** RegularExpression Id. */
  int ERROR_ACTION_LINK = 95;
  /** RegularExpression Id. */
  int ERROR_END = 96;
  /** RegularExpression Id. */
  int SECTION_FILTERS_NEXT_CONFIG = 97;
  /** RegularExpression Id. */
  int SECTION_FILTERS_NEXT_ACTIONS = 98;
  /** RegularExpression Id. */
  int SECTION_FILTERS_NEXT_ERRORS = 99;
  /** RegularExpression Id. */
  int SECTION_FILTERS_NEXT_FILTERS = 100;
  /** RegularExpression Id. */
  int SECTION_FILTERS_NEXT_EXTENSIONS = 101;
  /** RegularExpression Id. */
  int SECTION_FILTERS_NEXT_PROPERTIES = 102;
  /** RegularExpression Id. */
  int FILTER_METHOD = 103;
  /** RegularExpression Id. */
  int FILTER_PATH = 104;
  /** RegularExpression Id. */
  int FILTER_PATH_ALL = 105;
  /** RegularExpression Id. */
  int FILTER_SEPARATOR = 106;
  /** RegularExpression Id. */
  int FILTER_ACTION_BEGIN = 107;
  /** RegularExpression Id. */
  int FILTER_ACTION = 108;
  /** RegularExpression Id. */
  int FILTER_PARAMETERS_SEPARATOR = 109;
  /** RegularExpression Id. */
  int FILTER_PARAMETER_NAME = 110;
  /** RegularExpression Id. */
  int FILTER_PARAMETER_EQUALS = 111;
  /** RegularExpression Id. */
  int FILTER_PARAMETER_SEPARATOR = 112;
  /** RegularExpression Id. */
  int FILTER_END = 113;
  /** RegularExpression Id. */
  int FILTER_PARAMETER_VALUE = 114;
  /** RegularExpression Id. */
  int FILTER_PARAMETER_VALUE_SEPARATOR = 115;
  /** RegularExpression Id. */
  int FILTER_PARAMETER_VALUE_END = 116;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS_NEXT_CONFIG = 117;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS_NEXT_ACTIONS = 118;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS_NEXT_ERRORS = 119;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS_NEXT_FILTERS = 120;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS_NEXT_EXTENSIONS = 121;
  /** RegularExpression Id. */
  int SECTION_EXTENSIONS_NEXT_PROPERTIES = 122;
  /** RegularExpression Id. */
  int EXTENSION_PATH = 123;
  /** RegularExpression Id. */
  int EXTENSION_SEPARATOR = 124;
  /** RegularExpression Id. */
  int EXTENSION_FILE = 125;
  /** RegularExpression Id. */
  int EXTENSION_END = 126;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES_NEXT_CONFIG = 127;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES_NEXT_ACTIONS = 128;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES_NEXT_ERRORS = 129;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES_NEXT_FILTERS = 130;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES_NEXT_EXTENSIONS = 131;
  /** RegularExpression Id. */
  int SECTION_PROPERTIES_NEXT_PROPERTIES = 132;
  /** RegularExpression Id. */
  int PROPERTIE_NAME = 133;
  /** RegularExpression Id. */
  int PROPERTIE_EQUALS = 134;
  /** RegularExpression Id. */
  int PROPERTIE_VALUE = 135;
  /** RegularExpression Id. */
  int PROPERTIE_END = 136;
  /** RegularExpression Id. */
  int CHAR = 137;
  /** RegularExpression Id. */
  int CHAR_IN_CONFIG = 138;
  /** RegularExpression Id. */
  int CHAR_IN_CONFIG_VALUE = 139;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS = 140;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS_PATH_PARAMETERS = 141;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS_PATH_PARAMETER_VALUE = 142;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS_ACTION_JAVA = 143;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS_ACTION_VIEW = 144;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS_ACTION_LINK = 145;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS_PARAMETERS = 146;
  /** RegularExpression Id. */
  int CHAR_IN_ACTIONS_PARAMETER_VALUE = 147;
  /** RegularExpression Id. */
  int CHAR_IN_ERRORS = 148;
  /** RegularExpression Id. */
  int CHAR_IN_ERRORS_ACTIONS = 149;
  /** RegularExpression Id. */
  int CHAR_IN_FILTERS = 150;
  /** RegularExpression Id. */
  int CHAR_IN_FILTERS_PARAMETERS = 151;
  /** RegularExpression Id. */
  int CHAR_IN_FILTERS_PARAMETER_VALUE = 152;
  /** RegularExpression Id. */
  int CHAR_IN_EXTENSIONS = 153;
  /** RegularExpression Id. */
  int CHAR_IN_EXTENSIONS_FILE = 154;
  /** RegularExpression Id. */
  int CHAR_IN_PROPERTIES = 155;
  /** RegularExpression Id. */
  int CHAR_IN_PROPERTIES_VALUE = 156;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SECTION_CONFIG = 1;
  /** Lexical state. */
  int SECTION_ACTIONS = 2;
  /** Lexical state. */
  int SECTION_ERRORS = 3;
  /** Lexical state. */
  int SECTION_FILTERS = 4;
  /** Lexical state. */
  int SECTION_EXTENSIONS = 5;
  /** Lexical state. */
  int SECTION_PROPERTIES = 6;
  /** Lexical state. */
  int SECTION_CONFIG_VALUE = 7;
  /** Lexical state. */
  int SECTION_ACTIONS_PATH_PARAMETERS = 8;
  /** Lexical state. */
  int SECTION_ACTIONS_PATH_PARAMETER_VALUE = 9;
  /** Lexical state. */
  int SECTION_ACTIONS_ACTION_JAVA = 10;
  /** Lexical state. */
  int SECTION_ACTIONS_ACTION_VIEW = 11;
  /** Lexical state. */
  int SECTION_ACTIONS_ACTION_LINK = 12;
  /** Lexical state. */
  int SECTION_ACTIONS_PARAMETERS = 13;
  /** Lexical state. */
  int SECTION_ACTIONS_PARAMETER_VALUE = 14;
  /** Lexical state. */
  int SECTION_ERRORS_ACTIONS = 15;
  /** Lexical state. */
  int SECTION_FILTERS_PARAMETERS = 16;
  /** Lexical state. */
  int SECTION_FILTERS_PARAMETER_VALUE = 17;
  /** Lexical state. */
  int SECTION_EXTENSIONS_FILE = 18;
  /** Lexical state. */
  int SECTION_PROPERTIES_VALUE = 19;

  /** Literal token values. */
  String[] tokenImage = {
    "EOF",
    "comment",
    "comment",
    "comment",
    "comment",
    "comment",
    "comment",
    "comment",
    "section config",
    "section actions",
    "section errors",
    "section filters",
    "section extensions",
    "section properties",
    "methods HTTP",
    "method HTTP",
    "\"action:\"",
    "<ACTION_JAVA>",
    "\"view:\"",
    "<ACTION_LINK>",
    "<VARIABLE>",
    "<PATTERN>",
    "<IDENTIFIER>",
    "<QUALIFIED_IDENTIFIER>",
    "new line",
    "whitespace",
    "digit",
    "letter",
    "section config",
    "section actions",
    "section errors",
    "section filters",
    "section extensions",
    "section properties",
    "config key",
    "\"=\"",
    "config value",
    "new line",
    "section config",
    "section actions",
    "section errors",
    "section filters",
    "section extensions",
    "section properties",
    "methods HTTP",
    "<ACTION_PATH>",
    "<ACTION_PATH_VARIABLE>",
    "\"?\"",
    "<ACTION_ACTION_JAVA_BEGIN>",
    "<ACTION_ACTION_JAVA>",
    "<ACTION_ACTION_VIEW>",
    "<ACTION_ACTION_LINK>",
    "whitespace",
    "<ACTION_PATH_PARAMETER_NAME>",
    "\"=\"",
    "\"&\"",
    "<ACTION_PATH_PARAMETER_SEPARATOR>",
    "<ACTION_PATH_PARAMETER_VALUE>",
    "<ACTION_PATH_PARAMETER_VALUE_VARIABLE>",
    "\"&\"",
    "<ACTION_PATH_PARAMETER_VALUE_SEPARATOR>",
    "<ACTION_ACTION_JAVA_QUALIFIED_IDENTIFIER>",
    "<ACTION_ACTION_JAVA_IDENTIFIER>",
    "whitespace",
    "new line",
    "<ACTION_ACTION_VIEW_VALUE>",
    "whitespace",
    "new line",
    "<ACTION_ACTION_LINK_VALUE>",
    "whitespace",
    "new line",
    "<ACTION_PARAMETERS_SEPARATOR>",
    "<ACTION_PARAMETER_NAME>",
    "\"=\"",
    "\",\"",
    "new line",
    "<ACTION_PARAMETER_VALUE>",
    "\",\"",
    "<ACTION_PARAMETER_VALUE_END>",
    "section config",
    "section actions",
    "section errors",
    "section filters",
    "section extensions",
    "section properties",
    "\"code:\"",
    "<ERROR_CODE>",
    "\"*\"",
    "exception",
    "whitespace",
    "<ERROR_ACTION_JAVA_BEGIN>",
    "<ERROR_ACTION_VIEW_BEGIN>",
    "<ERROR_ACTION_LINK_BEGIN>",
    "<ERROR_ACTION_JAVA>",
    "<ERROR_ACTION_VIEW>",
    "<ERROR_ACTION_LINK>",
    "new line",
    "section config",
    "section actions",
    "section errors",
    "section filters",
    "section extensions",
    "section properties",
    "methods HTTP",
    "static path",
    "\"/*\"",
    "whitespace",
    "<FILTER_ACTION_BEGIN>",
    "<FILTER_ACTION>",
    "<FILTER_PARAMETERS_SEPARATOR>",
    "<FILTER_PARAMETER_NAME>",
    "\"=\"",
    "\",\"",
    "new line",
    "<FILTER_PARAMETER_VALUE>",
    "\",\"",
    "new line",
    "section config",
    "section actions",
    "section errors",
    "section filters",
    "section extensions",
    "section properties",
    "<EXTENSION_PATH>",
    "<EXTENSION_SEPARATOR>",
    "<EXTENSION_FILE>",
    "<EXTENSION_END>",
    "section config",
    "section actions",
    "section errors",
    "section filters",
    "section extensions",
    "section properties",
    "propertie name",
    "\"=\"",
    "propertie value",
    "new line",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
  };

}
